"""Add Comment to db

Revision ID: 3a46ad2adbb6
Revises: 2c19e54156af
Create Date: 2023-11-11 13:50:11.132451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a46ad2adbb6'
down_revision: Union[str, None] = '2c19e54156af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ads_comment_id_fkey', 'ads', type_='foreignkey')
    op.drop_column('ads', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ads_comment_id_fkey', 'ads', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
